p8105_hw1_SC6036
================
2026-09-25

## Loading Library

``` r
library(palmerpenguins)
```

    ## 
    ## Attaching package: 'palmerpenguins'

    ## The following objects are masked from 'package:datasets':
    ## 
    ##     penguins, penguins_raw

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.2.1     ✔ readr     2.2.0
    ## ✔ forcats   1.0.1     ✔ stringr   1.6.0
    ## ✔ ggplot2   4.0.3     ✔ tibble    3.3.1
    ## ✔ lubridate 1.9.5     ✔ tidyr     1.3.2
    ## ✔ purrr     1.2.2

    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

## Loading Data

``` r
data("penguins", package = "palmerpenguins")
penguins_df <- janitor::clean_names(penguins)
penguins_df
```

    ## # A tibble: 344 × 8
    ##    species island    bill_length_mm bill_depth_mm flipper_length_mm body_mass_g
    ##    <fct>   <fct>              <dbl>         <dbl>             <int>       <int>
    ##  1 Adelie  Torgersen           39.1          18.7               181        3750
    ##  2 Adelie  Torgersen           39.5          17.4               186        3800
    ##  3 Adelie  Torgersen           40.3          18                 195        3250
    ##  4 Adelie  Torgersen           NA            NA                  NA          NA
    ##  5 Adelie  Torgersen           36.7          19.3               193        3450
    ##  6 Adelie  Torgersen           39.3          20.6               190        3650
    ##  7 Adelie  Torgersen           38.9          17.8               181        3625
    ##  8 Adelie  Torgersen           39.2          19.6               195        4675
    ##  9 Adelie  Torgersen           34.1          18.1               193        3475
    ## 10 Adelie  Torgersen           42            20.2               190        4250
    ## # ℹ 334 more rows
    ## # ℹ 2 more variables: sex <fct>, year <int>

# Question 1

``` r
skimr::skim(penguins_df)
```

|                                                  |             |
|:-------------------------------------------------|:------------|
| Name                                             | penguins_df |
| Number of rows                                   | 344         |
| Number of columns                                | 8           |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |             |
| Column type frequency:                           |             |
| factor                                           | 3           |
| numeric                                          | 5           |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |             |
| Group variables                                  | None        |

Data summary

**Variable type: factor**

| skim_variable | n_missing | complete_rate | ordered | n_unique | top_counts |
|:---|---:|---:|:---|---:|:---|
| species | 0 | 1.00 | FALSE | 3 | Ade: 152, Gen: 124, Chi: 68 |
| island | 0 | 1.00 | FALSE | 3 | Bis: 168, Dre: 124, Tor: 52 |
| sex | 11 | 0.97 | FALSE | 2 | mal: 168, fem: 165 |

**Variable type: numeric**

| skim_variable | n_missing | complete_rate | mean | sd | p0 | p25 | p50 | p75 | p100 | hist |
|:---|---:|---:|---:|---:|---:|---:|---:|---:|---:|:---|
| bill_length_mm | 2 | 0.99 | 43.92 | 5.46 | 32.1 | 39.23 | 44.45 | 48.5 | 59.6 | ▃▇▇▆▁ |
| bill_depth_mm | 2 | 0.99 | 17.15 | 1.97 | 13.1 | 15.60 | 17.30 | 18.7 | 21.5 | ▅▅▇▇▂ |
| flipper_length_mm | 2 | 0.99 | 200.92 | 14.06 | 172.0 | 190.00 | 197.00 | 213.0 | 231.0 | ▂▇▃▅▂ |
| body_mass_g | 2 | 0.99 | 4201.75 | 801.95 | 2700.0 | 3550.00 | 4050.00 | 4750.0 | 6300.0 | ▃▇▆▃▂ |
| year | 0 | 1.00 | 2008.03 | 0.82 | 2007.0 | 2007.00 | 2008.00 | 2009.0 | 2009.0 | ▇▁▇▁▇ |

``` r
summary(penguins_df)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NAs    :2       NAs    :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NAs   : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NAs    :2         NAs    :2

``` r
ncol(penguins_df)
```

    ## [1] 8

``` r
nrow(penguins_df)
```

    ## [1] 344

``` r
mean(penguins_df$flipper_length_mm, na.rm = T)
```

    ## [1] 200.9152

``` r
ggplot(penguins_df, 
       aes(x = bill_length_mm, 
           y = flipper_length_mm, 
           color = species)) + 
  geom_point()
```

    ## Warning: Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_point()`).

![](p8105_hw1_SC6036_files/figure-gfm/Q1-1.png)<!-- -->

``` r
ggsave("scatterplot.png")
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_point()`).

This data set has 3 factor variables and 3 numeric variables. A few
important variable include `island`, `species`, `bill_length_mm`,
`bill_depth_mm`, `body_mass_g`, `sex`, and `year`. There are mostly
Adelie species (152 total) and mostly from the island Biscoe (168
total). The penguins data set has 344 rows and 8 columns. The mean
flipper length, after removing NA, is 200.9.

# Question 2

``` r
set.seed(1)
# setting seed for reproducibility and creating data frame

example_df = tibble(
  vec_numeric = rnorm(10),
  vec_logical = vec_numeric > 0,
  vec_char = sample(words, 10),
  vec_factor = factor(sample(c("level 1", "level 2", "level 3"), 10, replace = T))
)
example_df
```

    ## # A tibble: 10 × 4
    ##    vec_numeric vec_logical vec_char vec_factor
    ##          <dbl> <lgl>       <chr>    <fct>     
    ##  1      -0.626 FALSE       tax      level 2   
    ##  2       0.184 TRUE        over     level 2   
    ##  3      -0.836 FALSE       school   level 1   
    ##  4       1.60  TRUE        amount   level 3   
    ##  5       0.330 TRUE        bother   level 1   
    ##  6      -0.820 FALSE       seat     level 3   
    ##  7       0.487 TRUE        tonight  level 2   
    ##  8       0.738 TRUE        local    level 2   
    ##  9       0.576 TRUE        rather   level 2   
    ## 10      -0.305 FALSE       start    level 2

``` r
# taking means of variables
example_df |> pull(vec_numeric) |> mean()
```

    ## [1] 0.1322028

``` r
example_df |> pull(vec_logical) |> mean()
```

    ## [1] 0.6

``` r
example_df |> pull(vec_char)    |> mean()
```

    ## Warning in mean.default(pull(example_df, vec_char)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
example_df |> pull(vec_factor)  |> mean()
```

    ## Warning in mean.default(pull(example_df, vec_factor)): argument is not numeric
    ## or logical: returning NA

    ## [1] NA

`vec_numeric` and `vec_logical` work with the mean function, where the
first pulls the average and the second pulls the proportion of `True`.
`vec_char` does not work, as it is neither numeric nor logical,
therefore returning NA. Lastly, `vec_factor` does not work because a
factor is neither numeric nor logical, returning NA.

``` r
as.numeric(example_df$vec_logical)
as.numeric(example_df$vec_char)
as.numeric(example_df$vec_factor)

example_df |> pull(vec_logical) |> mean()
example_df |> pull(vec_char)    |> mean()
example_df |> pull(vec_factor)  |> mean()
```

`vec_logical` coerces to 0 and 1 which represents T and F, so we are
able to take the mean now, returning the mean. `vec_char` does not work
because the values have now become NA since they were previously words
and cannot become numerical, therefore returning NA. Lastly,
`vec_factor` looks like it becomes numerical because the levels are
given a number label, but taking the mean returns NA.

This does show how character to numeric coercion does not work, and that
a factor is neither numeric nor logical so the taking the mean won’t
work here either.
